
context("nsink_plot")
library(nsink)
library(sf)
load(system.file("testdata.rda", package="nsink"))
niantic_data$fdr <- terra::unwrap(niantic_data$fdr)
niantic_data$impervious <- terra::unwrap(niantic_data$impervious)
niantic_data$nlcd <- terra::unwrap(niantic_data$nlcd)
niantic_data$raster_template <- terra::unwrap(niantic_data$raster_template)
niantic_removal$raster_method$removal <- terra::unwrap(niantic_removal$raster_method$removal)
niantic_removal$raster_method$type <- terra::unwrap(niantic_removal$raster_method$type)
niantic_static <- nsink_generate_static_maps(niantic_data, niantic_removal,
                                             samp_dens = 3000)
test_that("plots plot", {
  expect_is(nsink_plot(niantic_static, "removal"), "list")
  expect_is(nsink_plot(niantic_static, "transport"), "list")
  expect_is(nsink_plot(niantic_static, "delivery"), "list")
  expect_is(nsink:::nsink_plot_delivery(niantic_static$delivery_idx), "list")
  expect_is(nsink:::nsink_plot_removal(niantic_static$removal_effic), "list")
  expect_is(nsink:::nsink_plot_transport(niantic_static$transport_idx), "list")
})
